perception_3d:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    max_obstacle_distance: 9999.0
    inscribed_radius: 0.5
    inflation_descending_rate: 2.0
    inflation_radius: 1.5
    sensors_collected_frequency: 5.0
    dgraph_publish_frequency: 1.0
    plugins: ["map", "path_blocked_strategy", "lidar", "depth_camera", "speed_limit_layer", "no_entry_layer"]
    map:
      plugin: "perception_3d::StaticLayer"
      use_adaptive_connection: false #If true: the neighbors of node is sparse, it will automatically increase search radius.
      adaptive_connection_number: 20
      radius_of_ground_connection: 1.5 #If use_adaptive_connection=false, the radius search of the node is applied.
      hollow_hole_tolerance: 16 #If there are small holes in the ground, and you want to ignore them, increase this value 
      intensity_search_radius: 1.0 #this value is suggested to be 1.0 meters, because if it is too large, the narrow passage will be miscalculated
      intensity_search_punish_weight: 0.1 #the weight for a node. Set this value higher means we dont like path planning cross a orphan node.
      static_imposing_radius: 1.0
    path_blocked_strategy:
      plugin: "perception_3d::PathBlockedStrategy"
      check_radius: 0.3
    lidar:
      plugin: "perception_3d::MultiLayerSpinningLidar"
      topic: "lslidar_point_cloud"
      pub_gbl_marking_for_visualization: false
      vertical_FOV_top: 5.0
      vertical_FOV_bottom: -15.0
      scan_effective_positive_start: 30.0
      scan_effective_positive_end: 180.0
      scan_effective_negative_start: -30.0
      scan_effective_negative_end: -180.0
      euclidean_cluster_extraction_tolerance: 0.3
      euclidean_cluster_extraction_min_cluster_size: 1
      euclidean_cluster_extraction_max_cluster_size: 100
      xy_resolution: 0.05
      height_resolution: 0.2
      marking_height: 1.0
      perception_window_size: 3.0 #the window for marking/clearing in meter, we dont casting to maximum range of the sensor even it is gbl map
      segmentation_ignore_ratio: 0.5 #f a segmentation match static pc with this ratio, we ignore it. ex: a wall
      is_local_planner: false
      expected_sensor_time: 0.2
    speed_limit_layer:
      plugin: "perception_3d::SpeedLimitLayer"
      speed_zone_pcd_file_dir: "/root/dddmr_navigation/src/dddmr_perception_3d/config/speed_limit_layer.yaml" #Abs path   
      knn_num_of_ground_search: 5
    no_entry_layer:
      plugin: "perception_3d::NoEntryLayer"
      no_entry_zone_pcd_file_dir: "/root/dddmr_navigation/src/dddmr_perception_3d/config/no_entry_layer.yaml" #Abs path   
      inflation_distance: 1.0
    depth_camera:
      plugin: "perception_3d::DepthCameraLayer"
      observation_sources: "camera_right"
      camera_right:
        topic: "/camera/camera/depth/color/points"
        sensor_frame: "camera_link"
        is_local_planner: false
        xy_resolution: 0.05
        height_resolution: 0.2
        observation_persistence: 0.0
        expected_update_rate: 0.1