perception_3d:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    max_obstacle_distance: 9999.0
    inscribed_radius: 0.5
    inflation_descending_rate: 2.0
    inflation_radius: 1.5
    sensors_collected_frequency: 10.0
    dgraph_publish_frequency: 1.0
    plugins: ["map", "depth_camera"]
    map:
      plugin: "perception_3d::StaticLayer"
      use_adaptive_connection: false #If true: the neighbors of node is sparse, it will automatically increase search radius.
      adaptive_connection_number: 20
      radius_of_ground_connection: 1.5 #If use_adaptive_connection=false, the radius search of the node is applied.
      hollow_hole_tolerance: 16 #If there are small holes in the ground, and you want to ignore them, increase this value 
      intensity_search_radius: 1.0 #this value is suggested to be 1.0 meters, because if it is too large, the narrow passage will be miscalculated
      intensity_search_punish_weight: 0.1 #the weight for a node. Set this value higher means we dont like path planning cross a orphan node.
      static_imposing_radius: 1.0
    depth_camera:
      plugin: "perception_3d::DepthCameraLayer"
      euclidean_cluster_extraction_tolerance: 0.1
      euclidean_cluster_extraction_min_cluster_size: 1
      xy_resolution: 0.05
      height_resolution: 0.2
      perception_window_size: 5.0 
      segmentation_ignore_ratio: 1.0
      observation_sources: "camera_left camera_right"
      camera_left:
        topic: "/depth2pc_left_node/point_cloud_from_depth"
        sensor_frame: "left_link"
        pub_gbl_marking_for_visualization: true
        is_local_planner: false
        observation_persistence: 0.0
        expected_update_rate: 0.1
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        obstacle_max_range: 5.0
        obstacle_min_range: 0.3
        FOV_W: 1.5184 #RS D455
        FOV_V: 1.0123 #RS D455
      camera_right:
        topic: "/depth2pc_left_node/point_cloud_from_depth"
        sensor_frame: "right_link"
        pub_gbl_marking_for_visualization: true
        is_local_planner: false
        observation_persistence: 0.0
        expected_update_rate: 0.1
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        obstacle_max_range: 5.0
        obstacle_min_range: 0.3
        FOV_W: 1.5184 #RS D455
        FOV_V: 1.0123 #RS D455